name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # allow workflow to be triggered manually
  workflow_dispatch:

jobs:
  #########################################################################
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: no-commit-to-branch
